spring.datasource.url=jdbc:postgresql://localhost:5432/autovoice
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

telegram.bot.username=autovoice_bot
telegram.bot.token=8067450476:AAEIprLs8Niq4kJtPlepxVb9eACc2XgJOQk

openai.api-key=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
openai.base-url=https://api.openai.com/v1
google.sheets.spreadsheet-id=1LMnaxTgdSfPQo24EuIbxEs6KePRZYxKplZ7ssc6jFj0
google.credentials.path=classpath:google-credentials.json