spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autovoice
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

google:
  sheets:
    spreadsheet-id: YOUR_SPREADSHEET_ID
    credentials-file: google-credentials.json

telegram:
  bot:
    token: YOUR_TELEGRAM_BOT_TOKEN
    username: YOUR_BOT_USERNAME